openapi: 3.0.0
info:
  title: WS-project
  description: This is a training project for an internship at WS.
  version: 1.0.0
servers:
  - url: "http://localhost:{port}/api/v1"
    description: Production
tags:
  - name: user
    description: User's pages
paths:
  /auth:
    post:
      tags:
        - user
      description: Authorization page
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
            example:
              email: test@test.com
              password: qwerty
      responses:
        '200':
          description: Successful authorization
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                success: true
                jwt: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2...'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              example:
                success: false
        default:
          description: Error
  /register:
    post:
      tags:
        - user
      description: Registration page
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
            example:
              name: admin
              email: test@test.com
              password: qwerty
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: string
              example:
                success: true
        '400':
          description: Registration error
          content:
            application/json:
              schema:
                type: string
              example:
                success: false
        default:
          description: Error
  /logout:
    get:
      tags:
        - user
      description: Logout
      responses:
        '200':
          description: Successful logout
          content:
            application/json:
              schema:
                type: string
              example:
                success: true
        default:
          description: Error
  /profile:
    get:
      tags:
        - user
      description: User's profile
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          description: User's id
          required: true
          example: 18
      responses:
        '200':
          description: Show user's proifle
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - type: integer
                    - type: string
              example:
                id: 18
                name: Tony
                gender: male
        default:
          description: Error
